version: 0.2

phases:
  pre_build:
    commands:
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
      - echo Ingresando a Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 800103408648.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - fecha=$(date -u +"%Y-%m-%d-%H-%M-%S-UTC")
      
  build:
    commands:
      - echo Creando imagen de Docker...
      - docker build -t 800103408648.dkr.ecr.us-east-1.amazonaws.com/hello-docker-image:latest .
      - echo analizando vulnerabilidades en imagen
      - trivy image --quiet --exit-code 1 --severity HIGH,CRITICAL --format html --output fecha.html 800103408648.dkr.ecr.us-east-1.amazonaws.com/hello-docker-image:latest
      - aws s3 cp fecha.html s3://trivy-vulnerabilities-reports   
      - echo Copiando imagen de Docker a repositorio...
      - docker push 800103408648.dkr.ecr.us-east-1.amazonaws.com/hello-docker-image:latest
